### ISSUE TITLE
Front card automatic orientation messes up layout

### ISSUE THREAD

**Issue by Lemodable** [ep1cman/DnD-Card-Generator#2] opened 2021-06-06 17:26 UTC
The front of the card automatically orients to best fit the aspect ratio of the image provided, but looks like the bottom border gets a little wonky

![2021-06-06](https://user-images.githubusercontent.com/85453006/120933901-cc175100-c6c1-11eb-96cf-75d6e8c518db.png)

**Comment by ep1cman** [comment] 2021-06-06 18:06
Huh, that’s definitely not right! Can you share the source image and data for that card with me and I will look into reproducing the issue.

**Comment by Lemodable** [comment] 2021-06-06 19:04
![Redbrand Ruffians](https://user-images.githubusercontent.com/85453006/120936889-f2dc8400-c6cf-11eb-96d2-cfa79c303211.jpg)

[srd.txt](https://github.com/ep1cman/DnD-Card-Generator/files/6604714/srd.txt)

**Comment by ep1cman** [comment] 2021-06-06 20:28
Ok I can confirm I get the same problem, a long with some others too. I will try fix them asap. Thanks for reporting the issue

**Comment by ep1cman** [comment] 2021-06-06 21:20
This should now be fixed as of b190ff1d1f93edaab018e92d908e8836f5326a7a. Please let me know if you still have issues related to this.

I have opened another issue #3 because I noticed the name in your provided data overflows the template instead of reducing the font size, but I will track that separately.

**Closed by ep1cman** 2021-06-06 21:20 UTC
